version: '2'

services:
  client:
    build: client
    ports:
      - "4200:4200"

  server:
    build: server
    ports:
      - "9000:9000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"